version: "3"
services:
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "YourPassword123"
            ACCEPT_EULA: "Y"
        ports:
            - "1589:1433"